assignment/assignment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forcast/', include('getWeather.urls'), name='main')
]

assignment/getWeather/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("", views.home, name= 'list'),
    path('data', views.forcastData, name='data')
]

assignment/getWeather/models.py
from django.db import models

class weatherData(models.Model):
    Latitude = models.FloatField(max_length=10)
    Longitude = models.FloatField(max_length=10)
    temperature = models.FloatField(max_length=5)

assignment/getWeather/forms.py
from django import forms

class coordinates(forms.Form):
    Latitude = forms.FloatField(max_value=90.0, min_value=-90.0)
    Longitude = forms.FloatField(max_value=180.0, min_value=-180.0)

assignment/getWeather/views.py
from django.http.response import HttpResponse
import requests
from django.shortcuts import render
from .forms import coordinates
from .models import weatherData

def home(request):
    return render(request, 'home.html')

def forcastData(request):
    if request.method== 'POST':

        # getting the input coordinates.
        rawData = coordinates(request.POST)
        if rawData.is_valid():
            lat = rawData.cleaned_data['Latitude']
            log = rawData.cleaned_data['Longitude']

            # accessing the api url to get the forcast url for the given coordinates.
            link = "https://api.weather.gov/points/{},{}".format(lat,log)
            response = requests.get(link)

            # validating whether coordinates are of USA or not.
            if 'status' in response.json() and response.json()['status'] == 404:
                return render(request, 'second.html')

            forcast_link = response.json()['properties']['forecast']

            #requesting server to send forcast details.
            forcast_details = requests.get(forcast_link)
            print(forcast_details.json().keys())
            tempretureDay = forcast_details.json()['properties']['periods'][1]['temperature']
            container = {'temp': tempretureDay,'lat':lat,'log':log}
            obj = weatherData(Latitude=lat, Longitude=log, temperature=tempretureDay)
            obj.save()
            return render(request, 'first.html', container)
        else:
            return HttpResponse("Invalid request", status = 500)

assignment/templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        #forcastMap {
            height: 400px;
        }
        body{
            background-color: darkslategray;
        }
    </style>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
   integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
   crossorigin=""
    />

    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
   integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
   crossorigin="">
    </script>
    <title>Forcast Data</title>

    
</head>
<body>
    <h1>Today's forcast data</h1>
    <h2>{{temp}} F</h2>
    <div id="forcastMap"></div>
    <script>
        // creating a map
        const mymap = L.map('forcastMap').setView([{{lat}}, {{log}}], 2.5);
        const attribution = '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>';
        const tileUrl = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';

        // creating a tile layer and adding it to map
        const tiles = L.tileLayer(tileUrl, {attribution});
        tiles.addTo(mymap)

        //creating a marker for our location
        const marker = L.marker([{{lat}}, {{log}}]).addTo(mymap);
        marker.bindPopup("<b>Temperature is: </b>{{temp}} F").openPopup();
    </script>
</body>
</html>

assignment/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weather Forcast</title>
    <style>
        img {
            width: 100%;
            height: 40vh;
        }
        body {
            background-color: darkgray;
        }      
        *, html {
            margin:0;
            padding:0;  
        }
        div {
            border: 5px solid ivory;
            border-radius: 6px;
            margin-top: 20px;
            padding-left: 40px;
            font-family: "Lucida Console", "Courier New", monospace;
            line-height: 1.5;
        }
    </style>
</head>
<body>
        <img src="https://source.unsplash.com/1600x900/?weather" alt="Error Loading Image">
        <div>
            <h2>Give us the coordinates and we will <br>share the forcast details(For USA Only)</h2>
            <form action="/forcast/data" method="POST">
                {% csrf_token %}
                <label for="id_Latitude">Latitude</label><br>
                <input type="text" name="Latitude" required id="id_Latitude"><br>
                <label for="id_Longitude">Longitude</label><br>
                <input type="text" name="Longitude" required id="id_Longitude"><br>
                <input type="submit" value="Submit">
            </form>
        </div>
</body>
</html>

assignment/templates/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invalid URL</title>
    <style>
        body{
            background-color: darkgray;
        }
    </style>
</head>
<body>
    <h1>Invalid coordinates.<br> Please Enter USA Specific Coordinates Only</h1>
</body>
</html>